version: '3'
services:
 minio:
  image: quay.io/minio/minio
  volumes:
   - ~/minio/data:/data
  ports:
   - 9000:9000
   - 9090:9090
  environment:
   MINIO_ADDRESS: ':9000'
   MINIO_CONSOLE_ADDRESS: ':9090'
  command: minio server /data
